import path from 'path';

export const dataFile = path.resolve(__dirname, '..', 'data', 'fixture.json');
export const clashesFile = path.resolve(__dirname, '..', 'data', 'clashes.json');
export const groundUsageFile = path.resolve(__dirname, '..', 'data', 'groundUsage.csv');

export const compMap = {
  '8 North 2021': 'U08 Mixed (North)',
  '8 South 2021': 'U08 Mixed (South)',
  '9 Black 2021': 'U09 Mixed (Black)',
  '9 Blue 2021': 'U09 Mixed (Blue)',
  '9 Green 2021': 'U09 Mixed (Green)',
  '9 Red 2021': 'U09 Mixed (Red)',
  '9 White 2021': 'U09 Mixed (White)',
  '10 Girls 2021': 'U10 Girls',
  '10 Black 2021': 'U10 Mixed (Black)',
  '10 Green 2021': 'U10 Mixed (Green)',
  '10 Red 2021 ': 'U10 Mixed (Red)',
  '10 White 2021': 'U10 Mixed (White)',
  '11A 2021': 'U11 Mixed (A)',
  '11B 2021': 'U11 Mixed (B)',
  '11C 2021': 'U11 Mixed (C)',
  '11D 2021': 'U11 Mixed (D)',
  '12A Girls 2021': 'U12 Girls (A)',
  '12B Girls 2021': 'U12 Girls (B)',
  '12A 2021': 'U12 Boys (A)',
  '12B 2021': 'U12 Boys (B)',
  '12C 2021 ': 'U12 Boys (C)',
  '12D 2021': 'U12 Boys (D)',
  '13A 2021': 'U13 Boys (A)',
  '13B 2021': 'U13 Boys (B)',
  '13C 2021': 'U13 Boys (C)',
  '13D 2021': 'U13 Boys (D)',
  '14A Girls 2021': 'U14 Girls (A)',
  '14B Girls 2021': 'U14 Girls (B)',
  '14C Girls 2021': 'U14 Girls (C)',
  '14A 2021': 'U14 Boys (A)',
  '14B 2021': 'U14 Boys (B)',
  '14C 2021': 'U14 Boys (C)',
  '14D 2021': 'U14 Boys (D)',
  '15A 2021': 'U15 Boys (A)',
  '15B 2021': 'U15 Boys (B)',
  '15C 2021': 'U15 Boys (C)',
  '15D 2021': 'U15 Boys (D)',
  'Deakin Uni 16A Girls 2021': 'U16 Girls (A)',
  'Deakin Uni 16B Girls 2021': 'U16 Girls (B)',
  'Deakin Uni 16C Girls 2021': 'U16 Girls (C)',
  '17 Premier 2021': 'U17 Boys (Premier)',
  '17A 2021': 'U17 Boys (A)',
  '17B 2021': 'U17 Boys (B)',
  '17C 2021': 'U17 Boys (C)',
  '17D 2021': 'U17 Boys (D)',
  'Deakin Uni 18 Premier Girls 2021': 'U18 Girls (Premier)',
  'Deakin Uni 18A Girls 2021': 'U18 Girls (A)',
};

export const venueMap = {
  'Ainslie Park': 'Ainslie Park',
  'Barngeong Reserve': 'Barngeong Reserve',
  'Batterham Reserve': 'Batterham Reserve',
  'Bayswater Junior Oval': 'Bayswater Junior Oval',
  'Bayswater Oval': 'Bayswater Senior Oval',
  'Belgrave South Recreation Reserve': 'Belgrave South Recreation Reserve',
  'Brentwood Reserve': 'Brentwood Reserve',
  'Central Reserve': 'Central Reserve',
  'Charles Green Reserve': 'Charles Green Reserve',
  'Coldstream Reserve': 'Coldstream Reserve',
  'Dobson Park': 'Dobson Park',
  'Donvale Reserve': 'Donvale Reserve',
  'East Burwood Reserve': 'East Burwood Reserve',
  'Eastfield Park': 'Eastfield Park',
  'Eildon Park': 'Eildon Park',
  'Forest Hill Reserve': 'Forest Hill Reserve',
  'HE Parker Reserve': 'HE Parker Reserve',
  'Heatherdale Reserve': 'Heatherdale Reserve',
  'Heights Reserve': 'Heights Reserve',
  'Jubilee Park': 'Jubilee Park',
  'Jubilee Park (Top Oval)': 'Jubilee Park (Top Oval)',
  'Kiloran Park': 'Kiloran Park',
  'Kimberley Reserve': 'Kimberley Reserve',
  'Knox Gardens Reserve': 'Knox Gardens Reserve',
  'Lakesfield Reserve': 'Lakesfield Reserve',
  'Lewis Park': 'Lewis Park',
  'Liberty Reserve': 'Liberty Reserve',
  'Lilydale Sports Oval': 'Lilydale Sports Oval',
  'Livingstone Primary School': 'Livingstone Primary School',
  'Miller Park': 'Miller Park',
  'Montrose Recreation Reserve': 'Montrose Recreation Reserve',
  'Montrose Reserve': 'Montrose Reserve',
  'Morton Park': 'Morton Park',
  'Mt Waverley Reserve': 'Mt Waverley Reserve',
  'Mullum Mullum Reserve': 'Mullum Mullum Reserve',
  'Narre Warren East Reserve': 'Narre Warren East Reserve',
  'Noble Park Reserve': 'Noble Park Reserve',
  'Pat Wright Senior Oval': 'Pat Wright Senior Oval',
  'Pinewood reserve': 'Pinewood reserve',
  'Pinks Reserve': 'Pinks Reserve',
  'Quambee Reserve': 'Quambee Reserve',
  'Ringwood North Reserve': 'Ringwood North Reserve',
  'Singleton Reserve': 'Singleton Reserve',
  'T.B.A.': 'T.B.A.',
  'Templeton Reserve': 'Templeton Reserve',
  'The Gateway Reserve': 'The Gateway Reserve',
  'Vermont Recreation Reserve': 'Vermont Recreation Reserve',
  'Walker Park': 'Walker Park',
  'Wally Tew Reserve': 'Wally Tew Reserve',
};

export const teamConfig = [
  { bullet: '🟢', team: 'U8 Mixed', compId: '597011', name: 'Bayswater' },
  { bullet: '🟡', team: 'U9 Mixed', compId: '597017', name: 'Bayswater' },
  { bullet: '🟢', team: 'U10 Mixed', compId: '597002', name: 'Bayswater' },
  { bullet: '🟡', team: 'U11 Mixed', compId: '596999', name: 'Bayswater/Kilsyth' },
  { bullet: '🟢', team: 'U12 Girls', compId: '596990', name: 'Bayswater' },
  { bullet: '🟡', team: 'U12 Boys', compId: '596966', name: 'Bayswater' },
  { bullet: '🟢', team: 'U13 Boys', compId: '596981', name: 'Bayswater' },
  { bullet: '🟡', team: 'U14 Girls', compId: '596975', name: 'Bayswater/Kilsyth' },
  { bullet: '🟢', team: 'U15 Boys', compId: '596982', name: 'Bayswater' },
  { bullet: '🟡', team: 'U16 Girls', compId: '596970', name: 'Bayswater' },
  { bullet: '🟢', team: 'U17 Boys', compId: '597001', name: 'Bayswater' },
  { bullet: '🟡', team: 'U18 Girls', compId: '596967', name: 'Rowville Knights/ Bayswater' },
];

export const roundConfig = [
  { number: 1, date: 'Sunday, April 10th, 2022' },
  { number: 2, date: 'Sunday, April 24th, 2022' },
  { number: 3, date: 'Sunday, May 1st, 2022' },
  { number: 4, date: 'Sunday, May 8th, 2022' },
  { number: 5, date: 'Sunday, May 15th, 2022' },
  { number: 6, date: 'Sunday, May 22nd, 2022' },
  { number: 7, date: 'Sunday, May 29th, 2022' },
  { number: 8, date: 'Sunday, June 5th, 2022' },
  { number: 9, date: 'Sunday, June 19th, 2022' },
  { number: 10, date: 'Sunday, June 26th, 2022' },
  { number: 11, date: 'Sunday, July 3rd, 2022' },
  { number: 12, date: 'Sunday, July 10th, 2022' },
  { number: 13, date: 'Sunday, July 17th, 2022' },
  { number: 14, date: 'Sunday, July 24th, 2022' },
];
